name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Use Node.js 20-compatible version
      - uses: actions/setup-python@v4  # Use Node.js 20-compatible version
      - name: Run pre-commit
        run: |
          pip install pre-commit
          git fetch origin

          # Check if event is a pull_request and if pre-commit config exists
          if [ "${{ github.event_name }}" == "pull_request" ] && [ -f .pre-commit-config.yaml ]; then
            pre-commit run --from-ref ${{ github.event.pull_request.base.ref }} --to-ref ${{ github.event.pull_request.head.sha }}
          elif [ -f .pre-commit-config.yaml ]; then  # Run for all files if it's a push or config exists
            pre-commit run --all-files
          else
            echo "No .pre-commit-config.yaml found, skipping pre-commit."
