name: Push Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Say Hello
        run: echo "Hello, world! This is a simple push workflow."
