name: Lint Models

on: [push]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
            python-version: "3.10"
      - name: Install SQLFluff
        run: "pip install sqlfluff==3.0.7"
      - name: Lint SQL file
        run: "sqlfluff lint models.sql --dialect postgres"
